# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.3.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Install Alectryon
        run: python3 -m pip install git+https://github.com/cpitclaudel/alectryon.git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Print Few ENV Variables
        run: |
          echo "${{ github.workspace }}"
          echo "GITHUB_WORKSPACE"
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/doc

      - name: Build SciLean
        run: lake build
      - name: Build Doc
        run: lake -Kenv=dev build SciLean:docs
      - name: Show packages
        run: ls $GITHUB_WORKSPACE/lean_packages
      - name: Copy SciLean toolchain to LeanInk
        run: cp $GITHUB_WORKSPACE/lean-toolchain $GITHUB_WORKSPACE/lean_packages/leanInk/lean-toolchain
      - name: Build LeanInk
        run: lake build --dir $GITHUB_WORKSPACE/lean_packages/leanInk
      - name: Link LeanInk to Path
        run: echo "$GITHUB_WORKSPACE/lean_packages/leanInk/build/bin" >> $GITHUB_PATH
#      - name: Build Literate Lean
#        run: alectryon --lake $GITHUB_WORKSPACE/lakefile.lean --output-directory $GITHUB_WORKSPACE/doc $GITHUB_WORKSPACE/doc/differentiation_in_scilean.lean
      - name: Content of build/doc
        run: ls $GITHUB_WORKSPACE/build/doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'

  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
